version: '3.1'

services:
  voipmonitor-sniffer:
    container_name: voipmonitor-hep
    image: sipcapture/hepsub-voipmonitor
    network_mode: "host"
    restart: always
    environment:
      - PUBLIC_IP=${PUBLIC_IP:-voipmonitor-hep}
      - PUBLIC_PORT=${PUBLIC_PORT:-18088}
      - HOMER_IP=${HOMER_IP:-homer-webapp}
      - HOMER_PORT=${HOMER_PORT:-9080}
    ports:
      - "18088:18088/tcp"
    volumes:
      - ./voipmonitor:/var/spool/voipmonitor

